// Sitemap index — lists all chunked sitemaps generated by app/sitemap.ts.
// Next.js generateSitemaps() emits /sitemap/{id}.xml but no top-level index;
// robots.txt points crawlers at /sitemap.xml, so we serve the index here.
export const revalidate = 86400

import { allClinics } from '@/data/all-clinics'
import { SITE_URL } from '@/lib/config'

// Must match CHUNK_SIZE in app/sitemap.ts
const CHUNK_SIZE = 5000

export async function GET() {
  const clinics = await allClinics
  const chunkCount = Math.max(1, Math.ceil(clinics.length / CHUNK_SIZE))
  const lastmod = new Date().toISOString().split('T')[0]

  const entries = Array.from({ length: chunkCount }, (_, i) =>
    `  <sitemap>\n    <loc>${SITE_URL}/sitemap/${i}.xml</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>`
  ).join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</sitemapindex>`

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=0, s-maxage=86400, stale-while-revalidate=86400',
    },
  })
}
