// AUTO-GENERATED by fix/seo-isr-recovery — do not edit manually
// Source: top_clinic_urls.txt (923 entries) + top_cities.tsv (40 entries)

export type ClinicParam = { city: string; slug: string }
export type CityParam = { city: string }

/** Top-priority clinic pages to pre-render at build time (ISR seed list) */
export const TOP_CLINIC_PARAMS: ClinicParam[] = [
  {
    "city": "addison",
    "slug": "upkeep-med-spa-addison-texas"
  },
  {
    "city": "alamo-heights",
    "slug": "san-antonio-med-spa-alamo-heights-alamo-heights-texas"
  },
  {
    "city": "alpharetta",
    "slug": "buket-aesthetics-wellness-alpharetta"
  },
  {
    "city": "alpharetta",
    "slug": "dermani-medspa-alpharetta-alpharetta"
  },
  {
    "city": "alpharetta",
    "slug": "natural-body-spa-med-spa-alpharetta-alpharetta"
  },
  {
    "city": "alpharetta",
    "slug": "palma-aesthetics-alpharetta"
  },
  {
    "city": "alpharetta",
    "slug": "sculpted-contours-medspa-alpharetta"
  },
  {
    "city": "alpharetta",
    "slug": "vie-riche-alpharetta"
  },
  {
    "city": "altamonte-springs",
    "slug": "4ever-young-med-spa-wellness-center-altamonte-springs-formerly-ideal-image-altamonte-springs"
  },
  {
    "city": "altamonte-springs",
    "slug": "aloever-medspa-altamonte-springs"
  },
  {
    "city": "altamonte-springs",
    "slug": "gkskinrenew-by-g-k-esthetic-and-wellness-center-llc-altamonte-springs"
  },
  {
    "city": "altamonte-springs",
    "slug": "laser-hair-removal"
  },
  {
    "city": "altamonte-springs",
    "slug": "nur-medspa-wellness-altamonte-springs-altamonte-springs"
  },
  {
    "city": "altamonte-springs",
    "slug": "oasis-esthetics-altamonte-springs"
  },
  {
    "city": "altamonte-springs",
    "slug": "rev-med-spa-altamonte-springs"
  },
  {
    "city": "altamonte-springs",
    "slug": "rev-med-spa-altamonte-springs-fl"
  },
  {
    "city": "arlington",
    "slug": "botox-fillers"
  },
  {
    "city": "arlington",
    "slug": "clinical-dermatology-center-arlington"
  },
  {
    "city": "arlington",
    "slug": "clinical-dermatology-center-arlington-va"
  },
  {
    "city": "arlington",
    "slug": "laser-hair-removal"
  },
  {
    "city": "arlington",
    "slug": "laser-of-arlington-arlington-va"
  },
  {
    "city": "arlington",
    "slug": "skin-pharm-arlington"
  },
  {
    "city": "arlington",
    "slug": "the-spa-clinic-arlington"
  },
  {
    "city": "arlington",
    "slug": "ultra-body-sculpt-arlington-virginia"
  },
  {
    "city": "atlanta",
    "slug": "a-bless-beauty-medspa-and-clinic-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "alc-ve-aesthetics-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "atlanta-medical-aesthetics-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "creme-de-la-body-llc-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "dermani-medspa-buckhead-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "dermani-medspa-summerhill-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "dermani-medspa-vinings-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "dermani-medspa-vinings-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "laser-aesthetics-career-institute-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "microneedling"
  },
  {
    "city": "atlanta",
    "slug": "muse-atlanta-skin-health-aesthetics-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "natural-body-spa-med-spa-morningside-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "radiance-medspa-atlanta-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "radiance-medspa-atlanta-atlanta-ga"
  },
  {
    "city": "atlanta",
    "slug": "radiance-medspa-atlanta-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "restore-wellness-and-medspa-atlanta-georgia"
  },
  {
    "city": "atlanta",
    "slug": "the-atlanta-aesthetician-aesthetics-of-atlanta-atlanta"
  },
  {
    "city": "atlanta",
    "slug": "uniquely-sculpted-bodies-atlanta-georgia"
  },
  {
    "city": "austin",
    "slug": "beaux-medspa-austin"
  },
  {
    "city": "austin",
    "slug": "body-tonic-rx-bee-cave-austin-texas"
  },
  {
    "city": "austin",
    "slug": "coolsculpting-austin-texas"
  },
  {
    "city": "austin",
    "slug": "fresh-aesthetics-austin"
  },
  {
    "city": "austin",
    "slug": "it-s-a-secret-med-spa-austin-south-lamar-austin-tx"
  },
  {
    "city": "austin",
    "slug": "nakedmd-med-spa-austin-austin"
  },
  {
    "city": "austin",
    "slug": "nakedmd-med-spa-austin-austin-texas"
  },
  {
    "city": "austin",
    "slug": "nakedmd-med-spa-austin-austin-tx"
  },
  {
    "city": "austin",
    "slug": "pure-medspa-austin-texas"
  },
  {
    "city": "austin",
    "slug": "the-medspa-austin-austin"
  },
  {
    "city": "austin",
    "slug": "transform-austin-med-spa-austin-texas"
  },
  {
    "city": "austin",
    "slug": "vio-med-spa-austin"
  },
  {
    "city": "austin",
    "slug": "westlake-aesthetics-wellness-austin"
  },
  {
    "city": "aventura",
    "slug": "beauty-medical-clinic-spa-aventura-fl"
  },
  {
    "city": "aventura",
    "slug": "bond-aesthetic-aventura-fl-aventura"
  },
  {
    "city": "aventura",
    "slug": "coolsculpting"
  },
  {
    "city": "aventura",
    "slug": "iv-therapy"
  },
  {
    "city": "aventura",
    "slug": "liquivida-wellness-center-aventura-aventura"
  },
  {
    "city": "aventura",
    "slug": "peptide-therapy"
  },
  {
    "city": "bal-harbour",
    "slug": "bal-harbour-wellness-bal-harbour"
  },
  {
    "city": "bal-harbour",
    "slug": "biotech-cosmetic-surgery-and-medical-spa-bal-harbour"
  },
  {
    "city": "bal-harbour",
    "slug": "comprehensive-medical-aesthetics-bal-harbour"
  },
  {
    "city": "bal-harbour",
    "slug": "medical-spa-buffalo-bal-harbour"
  },
  {
    "city": "bal-harbour",
    "slug": "medical-spa-buffalo-williamsville-bal-harbour"
  },
  {
    "city": "bal-harbour",
    "slug": "niya-bay-harbor-bal-harbour"
  },
  {
    "city": "bethesda",
    "slug": "excelsior-medspa-bethesda"
  },
  {
    "city": "beverly-hills",
    "slug": "alta-medispa-beverly-hills"
  },
  {
    "city": "beverly-hills",
    "slug": "botox-fillers"
  },
  {
    "city": "beverly-hills",
    "slug": "laser-hair-removal"
  },
  {
    "city": "blaine",
    "slug": "tc-medspa-laser-blaine-minnesota"
  },
  {
    "city": "bonita-springs",
    "slug": "bonita-med-spa-bonita-springs"
  },
  {
    "city": "bonita-springs",
    "slug": "facial-esthetique-med-spa-bonita-springs-bonita-springs"
  },
  {
    "city": "bonita-springs",
    "slug": "facial-esthetique-med-spa-bonita-springs-bonita-springs-fl"
  },
  {
    "city": "bonita-springs",
    "slug": "healthy-smiles-faces-facial-specialist-bonita-springs"
  },
  {
    "city": "bonita-springs",
    "slug": "hydrafacial"
  },
  {
    "city": "bonita-springs",
    "slug": "liquid-love-med-spa-bonita-springs-location-bonita-springs"
  },
  {
    "city": "bonita-springs",
    "slug": "microneedling"
  },
  {
    "city": "bonita-springs",
    "slug": "peptide-therapy"
  },
  {
    "city": "bonita-springs",
    "slug": "skin-aesthetics-of-swfl-bonita-springs"
  },
  {
    "city": "boston",
    "slug": "botox-fillers"
  },
  {
    "city": "boston",
    "slug": "luxury-aesthetics-center-boston"
  },
  {
    "city": "boston",
    "slug": "sev-laser-boston-massachusetts"
  },
  {
    "city": "boston",
    "slug": "shah-wellness-and-medspa-boston"
  },
  {
    "city": "boston",
    "slug": "vio-med-spa-boston-south-end-boston"
  },
  {
    "city": "boynton-beach",
    "slug": "botox-fillers"
  },
  {
    "city": "boynton-beach",
    "slug": "remedie-boynton-beach-fl"
  },
  {
    "city": "bradenton",
    "slug": "hydrafacial"
  },
  {
    "city": "bradenton",
    "slug": "laser-hair-removal"
  },
  {
    "city": "bradenton",
    "slug": "the-aesthetics-lounge-and-spa-lakewood-ranch-bradenton-fl"
  },
  {
    "city": "brandon",
    "slug": "aurabella-med-spa-brandon"
  },
  {
    "city": "brandon",
    "slug": "blu-indigo-spa-wellness-brandon"
  },
  {
    "city": "brandon",
    "slug": "fraiche-medspa-brandon"
  },
  {
    "city": "brandon",
    "slug": "happy-massage-of-brandon-brandon"
  },
  {
    "city": "brandon",
    "slug": "holli-aesthetics-valrico-brandon"
  },
  {
    "city": "brandon",
    "slug": "microneedling"
  },
  {
    "city": "brandon",
    "slug": "mira-med-spa-brandon"
  },
  {
    "city": "brandon",
    "slug": "refresh-brandon-medical-aesthetics-formerly-ideal-image-brandon"
  },
  {
    "city": "brandon",
    "slug": "refresh-brandon-medical-aesthetics-formerly-ideal-image-brandon-fl"
  },
  {
    "city": "brandon",
    "slug": "revita-body-care-brandon"
  },
  {
    "city": "brandon",
    "slug": "st-jude-medical-center-and-aesthetic-center-brandon"
  },
  {
    "city": "buckhead",
    "slug": "buckhead-facial-plastic-surgery-theresa-m-jarmuz-md-buckhead"
  },
  {
    "city": "buckhead",
    "slug": "clear-aesthetics-md-buckhead"
  },
  {
    "city": "buckhead",
    "slug": "dermani-medspa-north-buckhead-buckhead"
  },
  {
    "city": "buckhead",
    "slug": "facial-aesthetics-buckhead"
  },
  {
    "city": "buckhead",
    "slug": "facial-aesthetics-buckhead-ga"
  },
  {
    "city": "buckhead",
    "slug": "hydrafacial"
  },
  {
    "city": "cambridge",
    "slug": "bio-esthetics-cambridge-massachusetts"
  },
  {
    "city": "cape-coral",
    "slug": "refresh-medspa-cape-coral-fl"
  },
  {
    "city": "chandler",
    "slug": "honor-aesthetics-and-wellness-chandler"
  },
  {
    "city": "charlotte",
    "slug": "beautox-and-fillers-of-charlotte-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "botox-fillers"
  },
  {
    "city": "charlotte",
    "slug": "charlotte-medical-aesthetics-charlotte-nc"
  },
  {
    "city": "charlotte",
    "slug": "coolsculpting"
  },
  {
    "city": "charlotte",
    "slug": "dermani-medspa-ballantyne-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "eden-medspa-charlotte"
  },
  {
    "city": "charlotte",
    "slug": "infinity-medspa-and-wellness-charlotte-nc"
  },
  {
    "city": "charlotte",
    "slug": "inshapemd-ballantyne-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "laser-hair-removal"
  },
  {
    "city": "charlotte",
    "slug": "medispa-charlotte-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "miramae-medical-skin-care-studio-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "modern-skin-laser-clinic-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "prime-iv-hydration-wellness-ballantyne-nc-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "semper-laser-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "skin-lab-charlotte"
  },
  {
    "city": "charlotte",
    "slug": "the-maxim-clinic-south-end-charlotte"
  },
  {
    "city": "charlotte",
    "slug": "trt-testosterone"
  },
  {
    "city": "charlotte",
    "slug": "truwellness-charlotte-charlotte-north-carolina"
  },
  {
    "city": "charlotte",
    "slug": "weight-loss-ozempic"
  },
  {
    "city": "chicago",
    "slug": "ageless-medspa-chicago-illinois"
  },
  {
    "city": "chicago",
    "slug": "chamber-of-wellness-direct-primary-care-and-weight-loss-chicago-illinois"
  },
  {
    "city": "chicago",
    "slug": "chapter-aesthetic-studio-chicago"
  },
  {
    "city": "chicago",
    "slug": "chicago-aesthetics-chicago"
  },
  {
    "city": "chicago",
    "slug": "liv-aesthetics-chicago-chicago"
  },
  {
    "city": "chicago",
    "slug": "northwestern-med-spa-river-north-chicago-illinois"
  },
  {
    "city": "chicago",
    "slug": "old-town-med-spa-chicago"
  },
  {
    "city": "chicago",
    "slug": "old-town-med-spa-lincoln-park-chicago-il"
  },
  {
    "city": "chicago",
    "slug": "old-town-med-spa-lincoln-park-chicago-illinois"
  },
  {
    "city": "chicago",
    "slug": "wrinkle-fairy-chicago-illinois"
  },
  {
    "city": "clearwater",
    "slug": "chemical-peels"
  },
  {
    "city": "clearwater",
    "slug": "luma-dermatology-clearwater-fl"
  },
  {
    "city": "clearwater",
    "slug": "tide-med-spa-clearwater-fl"
  },
  {
    "city": "coconut-creek",
    "slug": "beauty-avenue-salon-fl-coconut-creek"
  },
  {
    "city": "coconut-creek",
    "slug": "bleu-nail-spas-coconut-creek"
  },
  {
    "city": "coconut-creek",
    "slug": "bliss-bloom-salon-spa-boutique-coconut-creek"
  },
  {
    "city": "coconut-creek",
    "slug": "doctor-bg-med-excellence-health-well-being-and-longevity-coconut-creek-fl"
  },
  {
    "city": "coconut-creek",
    "slug": "laser-love-med-spa-coconut-creek"
  },
  {
    "city": "coconut-creek",
    "slug": "nova-wellness-center-coconut-creek"
  },
  {
    "city": "coconut-creek",
    "slug": "well-labs-medspa-coconut-creek-formerly-hello-gorgeous-coconut-creek"
  },
  {
    "city": "columbus",
    "slug": "a-younger-you-aesthetics-med-spa-powell-oh-columbus"
  },
  {
    "city": "columbus",
    "slug": "columbus-aesthetic-plastic-surgery-gahanna-columbus"
  },
  {
    "city": "columbus",
    "slug": "columbus-aesthetic-plastic-surgery-upper-arlington-columbus-oh"
  },
  {
    "city": "columbus",
    "slug": "em-zen-aesthetic-medicine-precision-wellness-upper-arlington-columbus"
  },
  {
    "city": "columbus",
    "slug": "face-forward-aesthetics-columbus"
  },
  {
    "city": "columbus",
    "slug": "hydrate-me-medspa-new-albany-columbus"
  },
  {
    "city": "columbus",
    "slug": "iv-therapy"
  },
  {
    "city": "columbus",
    "slug": "julieann-aesthetic-medicine-columbus"
  },
  {
    "city": "columbus",
    "slug": "the-luxe-medspa-aesthetics-bodycare-columbus"
  },
  {
    "city": "concord",
    "slug": "luxderm-medspa-concord-massachusetts"
  },
  {
    "city": "cooper-city",
    "slug": "dermamag-aesthetics-academy-cooper-city"
  },
  {
    "city": "cooper-city",
    "slug": "elegant-laser-aesthetics-spa-beauty-cafe-cooper-city-cooper-city"
  },
  {
    "city": "cooper-city",
    "slug": "priority-health-md-roberto-fernandez-blay-md-cooper-city"
  },
  {
    "city": "coral-gables",
    "slug": "botox-fillers"
  },
  {
    "city": "coral-gables",
    "slug": "chemical-peels"
  },
  {
    "city": "coral-gables",
    "slug": "medicalia-miami-med-spa-aesthetics-coral-gables-fl"
  },
  {
    "city": "coral-gables",
    "slug": "microneedling"
  },
  {
    "city": "cutler-bay",
    "slug": "chiyan-medical-group-cutler-bay"
  },
  {
    "city": "cutler-bay",
    "slug": "glou-advanced-aesthetics-cutler-bay"
  },
  {
    "city": "cutler-bay",
    "slug": "hair-ego-cutler-bay"
  },
  {
    "city": "cutler-bay",
    "slug": "selfistry-mdspa-cutler-bay"
  },
  {
    "city": "dallas",
    "slug": "dermani-medspa-preston-hollow-dallas"
  },
  {
    "city": "dallas",
    "slug": "dermani-medspa-preston-hollow-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "hello-nurse-mobile-iv-services-we-come-to-you-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "hydrafacial"
  },
  {
    "city": "dallas",
    "slug": "just-injected-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "laser-hair-removal"
  },
  {
    "city": "dallas",
    "slug": "lisse-aesthetics-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "microneedling"
  },
  {
    "city": "dallas",
    "slug": "mskin-med-spa-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "nakedmd-med-spa-dallas-dallas"
  },
  {
    "city": "dallas",
    "slug": "nakedmd-med-spa-dallas-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "regen-aesthetics-concierge-of-texas-dallas-texas"
  },
  {
    "city": "dallas",
    "slug": "renew-beauty-dallas-tx"
  },
  {
    "city": "dallas",
    "slug": "upkeep-med-spa-dallas"
  },
  {
    "city": "davie",
    "slug": "beautification-co-davie"
  },
  {
    "city": "davie",
    "slug": "brows-beyond-lounge-davie"
  },
  {
    "city": "davie",
    "slug": "davie-designer-dental-davie"
  },
  {
    "city": "davie",
    "slug": "elixir-aesthetics-wellness-davie"
  },
  {
    "city": "davie",
    "slug": "facial-healing-by-adi-davie-fl"
  },
  {
    "city": "davie",
    "slug": "iv-therapy"
  },
  {
    "city": "davie",
    "slug": "mize-med-spa-and-wellness-center-davie"
  },
  {
    "city": "davie",
    "slug": "queen-24k-med-spa-davie"
  },
  {
    "city": "davie",
    "slug": "simply-massage-davie"
  },
  {
    "city": "davie",
    "slug": "skin-medical-equipment-davie"
  },
  {
    "city": "davie",
    "slug": "ys-aesthetics-davie"
  },
  {
    "city": "daytona-beach",
    "slug": "laser-hair-removal"
  },
  {
    "city": "deerfield-beach",
    "slug": "aesthetic-and-anti-aging-medical-center-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "anna-fernandez-corpus-aesthetic-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "ashleys-medical-aesthetics-deerfield-beach-fl"
  },
  {
    "city": "deerfield-beach",
    "slug": "best-shape-med-spa-pompano-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "elite-skin-aesthetics-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "green-dermatology-cosmetic-center-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "harrington-aesthetics-deerfield-beach-fl"
  },
  {
    "city": "deerfield-beach",
    "slug": "medstation-pompano-a-cl-nica-do-brasileiro-no-mundo-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "microneedling"
  },
  {
    "city": "deerfield-beach",
    "slug": "mohs-skin-cancer-surgery-boca-raton-deerfield-beach-fl"
  },
  {
    "city": "deerfield-beach",
    "slug": "navarro-medical-centers-deerfield-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "skin-body-space-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "skin-club-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "skin-rejuvenation-deerfield-beach"
  },
  {
    "city": "deerfield-beach",
    "slug": "the-cream-skin-facial-lash-studio-in-deerfield-beach-fl-hydrofacial-deep-cleansing-acne-anti-aging-lash-extensions-deerfield-beach"
  },
  {
    "city": "delray-beach",
    "slug": "dermaveda-aesthetics-wellness-delray-beach-delray-beach-fl"
  },
  {
    "city": "deltona",
    "slug": "kadia-medical-deltona"
  },
  {
    "city": "deltona",
    "slug": "z-family-and-cosmetic-dentistry-formerly-steven-j-smith-dmd-deltona"
  },
  {
    "city": "denver",
    "slug": "allure-med-spa-denver-colorado"
  },
  {
    "city": "denver",
    "slug": "kya-iv-aesthetics-denver-colorado"
  },
  {
    "city": "denver",
    "slug": "let-s-face-it-med-spa-denver-colorado"
  },
  {
    "city": "denver",
    "slug": "liv-medspa-denver-colorado"
  },
  {
    "city": "denver",
    "slug": "rejuvenate-medspa-denver"
  },
  {
    "city": "denver",
    "slug": "revive-medical-spa-denver-co-denver-colorado"
  },
  {
    "city": "denver",
    "slug": "simply-injectables-denver"
  },
  {
    "city": "denver",
    "slug": "simply-injectables-denver-colorado"
  },
  {
    "city": "denver",
    "slug": "spa-bella-medispa-denver"
  },
  {
    "city": "denver",
    "slug": "the-luxe-room-rino-denver-colorado"
  },
  {
    "city": "destin",
    "slug": "asian-massage-destin"
  },
  {
    "city": "destin",
    "slug": "botox-fillers"
  },
  {
    "city": "destin",
    "slug": "the-mens-den-and-med-spa-by-om-relaxation-spa-destin-fl"
  },
  {
    "city": "edina",
    "slug": "milan-laser-hair-removal-edina-minnesota"
  },
  {
    "city": "edina",
    "slug": "pure-lux-medspa-edina-minnesota"
  },
  {
    "city": "encinitas",
    "slug": "better-off-medspa-and-weight-loss-encinitas-california"
  },
  {
    "city": "estero",
    "slug": "azul-cosmetic-surgery-and-medical-spa-bonita-springs-estero"
  },
  {
    "city": "estero",
    "slug": "nouveau-med-spa-estero-estero"
  },
  {
    "city": "estero",
    "slug": "peptide-therapy"
  },
  {
    "city": "estero",
    "slug": "restore-hyper-wellness-estero"
  },
  {
    "city": "estero",
    "slug": "sunset-massage-estero"
  },
  {
    "city": "farmers-branch",
    "slug": "ivtherapy2go-24-7-mobile-iv-bar-farmers-branch-texas"
  },
  {
    "city": "fisher-island",
    "slug": "bay-harbor-med-spa-laser-hair-removal-electrolysis-fisher-island"
  },
  {
    "city": "fisher-island",
    "slug": "dermaspalogy-fisher-island"
  },
  {
    "city": "fisher-island",
    "slug": "kauai-aesthetics-fisher-island"
  },
  {
    "city": "fisher-island",
    "slug": "las-olas-med-spa-fisher-island"
  },
  {
    "city": "fisher-island",
    "slug": "mauna-lani-medical-aesthetics-bio-rejuvenation-center-fisher-island"
  },
  {
    "city": "fisher-island",
    "slug": "the-med-spa-of-new-smyrna-beach-beachside-fisher-island"
  },
  {
    "city": "fisher-island",
    "slug": "the-med-spa-of-new-smyrna-beach-mainside-fisher-island"
  },
  {
    "city": "fort-lauderdale",
    "slug": "essential-aesthetics-health-fort-lauderdale-fl"
  },
  {
    "city": "fort-myers",
    "slug": "botox-fillers"
  },
  {
    "city": "fort-myers",
    "slug": "chemical-peels"
  },
  {
    "city": "fort-myers",
    "slug": "laser-hair-removal"
  },
  {
    "city": "fort-myers",
    "slug": "peptide-therapy"
  },
  {
    "city": "fort-myers",
    "slug": "trt-testosterone"
  },
  {
    "city": "fort-pierce",
    "slug": "botox-fillers"
  },
  {
    "city": "fort-pierce",
    "slug": "hydrafacial"
  },
  {
    "city": "fort-pierce",
    "slug": "laser-hair-removal"
  },
  {
    "city": "fort-pierce",
    "slug": "regenerative-medical-group-fort-pierce"
  },
  {
    "city": "fort-pierce",
    "slug": "rn-laser-med-spa-fort-pierce"
  },
  {
    "city": "fort-pierce",
    "slug": "the-skin-spot-laser-aesthetics-fort-pierce"
  },
  {
    "city": "fort-pierce",
    "slug": "trusted-care-aesthetics-fort-pierce"
  },
  {
    "city": "fort-walton-beach",
    "slug": "rejuvenation-medical-spa-in-aesthetics-fort-walton-beach"
  },
  {
    "city": "fort-walton-beach",
    "slug": "source-institute-massage-school-therapeutic-bodywork-of-fort-walton-beach-fort-walton-beach"
  },
  {
    "city": "fort-walton-beach",
    "slug": "the-aesthetic-health-wellness-collective-fort-walton-beach"
  },
  {
    "city": "fort-walton-beach",
    "slug": "thrive-wellness-fort-walton-beach"
  },
  {
    "city": "fort-worth",
    "slug": "clearchoice-dental-implant-center-fort-worth"
  },
  {
    "city": "fort-worth",
    "slug": "nakedmd-med-spa-fort-worth-fort-worth"
  },
  {
    "city": "fort-worth",
    "slug": "nakedmd-med-spa-fort-worth-fort-worth-tx"
  },
  {
    "city": "framingham",
    "slug": "medical-spa-by-nurse-fiona-framingham-massachusetts"
  },
  {
    "city": "gainesville",
    "slug": "accent-aesthetics-gainesville-fl"
  },
  {
    "city": "gainesville",
    "slug": "elite-medispa-town-of-tioga-gainesville-fl"
  },
  {
    "city": "gainesville",
    "slug": "laser-hair-removal"
  },
  {
    "city": "gainesville",
    "slug": "laser-skin-care-center-of-gainesville-gainesville-fl"
  },
  {
    "city": "gainesville",
    "slug": "microneedling"
  },
  {
    "city": "glendale",
    "slug": "valley-medical-weight-loss-glendale-glendale-arizona"
  },
  {
    "city": "golden-valley",
    "slug": "minneapolis-anti-aging-skin-clinic-golden-valley-minnesota"
  },
  {
    "city": "hallandale-beach",
    "slug": "bogat-aesthetics-wellness-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "botox-filler-lab-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "botox-filler-lab-hallandale-beach-fl"
  },
  {
    "city": "hallandale-beach",
    "slug": "botox-fillers"
  },
  {
    "city": "hallandale-beach",
    "slug": "delice-med-spa-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "lala-rivers-hair-salon-spa-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "privilege-dental-studio-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "silk-skin-medspa-vitamin-iv-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "toxwell-med-spa-and-wellness-hallandale-beach-fl"
  },
  {
    "city": "hallandale-beach",
    "slug": "univida-hallandale-medical-centers-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "vital-medspa-morpheus8-burst-specialist-hallandale-beach"
  },
  {
    "city": "hallandale-beach",
    "slug": "wo-man-luxe-med-spa-hallandale-beach"
  },
  {
    "city": "henderson",
    "slug": "elite-image-one-med-spa-anthem-seven-hills-henderson"
  },
  {
    "city": "henderson",
    "slug": "remarkable-aesthetics-henderson"
  },
  {
    "city": "hialeah",
    "slug": "casablanca-medical-hialeah-hialeah"
  },
  {
    "city": "hialeah",
    "slug": "eltk-med-pro-elecctrika-corp-hialeah-fl"
  },
  {
    "city": "hialeah",
    "slug": "venus-health-beauty-center-hialeah"
  },
  {
    "city": "hialeah",
    "slug": "yamibeautylaser-hialeah"
  },
  {
    "city": "hialeah",
    "slug": "ziba-renewal-studio-hialeah"
  },
  {
    "city": "houston",
    "slug": "4ever-young-med-spa-wellness-center-vintage-park-houston-texas"
  },
  {
    "city": "houston",
    "slug": "alabama-med-spa-by-voupre-houston"
  },
  {
    "city": "houston",
    "slug": "botox-fillers"
  },
  {
    "city": "houston",
    "slug": "glow-medspa-houston-houston"
  },
  {
    "city": "houston",
    "slug": "glow-medspa-houston-houston-texas"
  },
  {
    "city": "houston",
    "slug": "houston-medical-wellness-weight-loss-clinic-houston-texas"
  },
  {
    "city": "houston",
    "slug": "houston-weight-loss-center-heights-houston-texas"
  },
  {
    "city": "houston",
    "slug": "iv-therapy"
  },
  {
    "city": "houston",
    "slug": "laser-hair-removal"
  },
  {
    "city": "houston",
    "slug": "lifesculpt-longevity-aesthetics-galleria-houston-texas"
  },
  {
    "city": "houston",
    "slug": "microneedling"
  },
  {
    "city": "houston",
    "slug": "nakedmd-med-spa-houston-houston-texas"
  },
  {
    "city": "houston",
    "slug": "peak-health-aesthetics-houston-texas"
  },
  {
    "city": "houston",
    "slug": "revived-personalized-wellness-houston-texas"
  },
  {
    "city": "houston",
    "slug": "the-skin-clinic-houston-tx"
  },
  {
    "city": "houston",
    "slug": "vigor-health-testosterone-and-weight-loss-houston-texas"
  },
  {
    "city": "jacksonville-beach",
    "slug": "laser-skin-solutions-jacksonville-jacksonville-beach"
  },
  {
    "city": "jacksonville",
    "slug": "botox-fillers"
  },
  {
    "city": "jacksonville",
    "slug": "hydro-med-spa-jacksonville-fl"
  },
  {
    "city": "jacksonville",
    "slug": "microneedling"
  },
  {
    "city": "jupiter",
    "slug": "alluramd-aesthetics-wellness-jupiter-formerly-truwellnessmd-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "beauty-boutique-salon-and-medi-spa-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "beem-light-sauna-jupiter-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "dermalux-aesthetics-llc-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "elevated-wellness-by-dr-leah-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "hydrafacial-expert-by-vivian-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "inlet-craniosacral-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "jupiter-dermatology-hair-restoration-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "laser-and-beauty-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "luxe-spa-services-by-leena-llc-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "medicus-aesthetics-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "michelle-dimartini-aesthteics-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "ml-aesthetics-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "molle-aesthetics-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "perizia-aesthetics-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "prana-blue-aesthetics-kimberly-wojtusik-aprn-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "refresh-palm-beach-medical-aesthetics-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "the-brain-spa-llc-jupiter"
  },
  {
    "city": "jupiter",
    "slug": "tighter-lines-aesthetics-jupiter"
  },
  {
    "city": "kendall",
    "slug": "west-kendall-aesthetic-laser-center-kendall-fl"
  },
  {
    "city": "key-biscayne",
    "slug": "beauty-first-med-spa-key-biscayne"
  },
  {
    "city": "key-biscayne",
    "slug": "divina-medspa-key-biscayne"
  },
  {
    "city": "key-biscayne",
    "slug": "hollywood-laser-med-spa-key-biscayne"
  },
  {
    "city": "key-biscayne",
    "slug": "juventas-by-annie-key-biscayne"
  },
  {
    "city": "key-biscayne",
    "slug": "keys-med-spa-key-biscayne"
  },
  {
    "city": "key-biscayne",
    "slug": "laser-skin-medical-edgewater-key-biscayne"
  },
  {
    "city": "key-biscayne",
    "slug": "miami-surgical-medspa-key-biscayne"
  },
  {
    "city": "key-west",
    "slug": "iv-hydration-stations-key-west"
  },
  {
    "city": "key-west",
    "slug": "jennifer-fox-esthetician-key-west"
  },
  {
    "city": "key-west",
    "slug": "new-you-health-clinic-pllc-key-west"
  },
  {
    "city": "key-west",
    "slug": "paradise-dental-care-key-west"
  },
  {
    "city": "kissimmee",
    "slug": "all-body-spa-by-yeliz-kissimmee-fl"
  },
  {
    "city": "kissimmee",
    "slug": "healing-skin-medical-aesthetics-kissimmee-fl"
  },
  {
    "city": "la-jolla",
    "slug": "san-diego-skin-medspa-laser-la-jolla-california"
  },
  {
    "city": "lake-oswego",
    "slug": "prime-iv-hydration-wellness-lake-oswego-or-lake-oswego-oregon"
  },
  {
    "city": "lake-worth",
    "slug": "bellanova-cosmetic-surgery-lake-worth-fl"
  },
  {
    "city": "lake-worth",
    "slug": "body-care-med-spa-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "din-style-wpb-lake-worth-fl"
  },
  {
    "city": "lake-worth",
    "slug": "doc-hans-urgent-dental-care-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "dr-robert-l-denton-dds-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "elizabeth-dominican-hair-salon-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "endro-lake-worth-fl"
  },
  {
    "city": "lake-worth",
    "slug": "eye-candy-laser-wellness-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "eye-candy-laser-wellness-lake-worth-fl"
  },
  {
    "city": "lake-worth",
    "slug": "fabian-andrey-massage-therapy-body-sculpting-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "liberto-therapy-llc-lake-worth"
  },
  {
    "city": "lake-worth",
    "slug": "redefined-beauty-lake-worth-fl"
  },
  {
    "city": "lake-worth",
    "slug": "the-well-being-lounge-palm-beach-lake-worth"
  },
  {
    "city": "lakeland",
    "slug": "beauty-beyond-aesthetics-lakeland-med-spa-lakeland"
  },
  {
    "city": "lakeland",
    "slug": "daydreams-day-spa-massage-lakeland-fl-lakeland"
  },
  {
    "city": "lakeland",
    "slug": "hydrafacial"
  },
  {
    "city": "lakeland",
    "slug": "microneedling"
  },
  {
    "city": "lakeland",
    "slug": "peptide-therapy"
  },
  {
    "city": "lakeland",
    "slug": "the-skin-boutique-lakeland-fl"
  },
  {
    "city": "lakeland",
    "slug": "trt-testosterone"
  },
  {
    "city": "lakewood",
    "slug": "injectables-by-selena-lakewood-colorado"
  },
  {
    "city": "land-o-lakes",
    "slug": "creations-med-aesthetics-and-wellness-spa-land-o-lakes"
  },
  {
    "city": "land-o-lakes",
    "slug": "luxux-suites-and-med-spa-land-o-lakes"
  },
  {
    "city": "land-o-lakes",
    "slug": "mynt-aesthetics-land-o-lakes"
  },
  {
    "city": "largo",
    "slug": "adonis-face-body-spa-4-men-largo"
  },
  {
    "city": "largo",
    "slug": "bella-therapy-asian-massage-largo-fl"
  },
  {
    "city": "largo",
    "slug": "dermafix-spa-largo-fl-largo"
  },
  {
    "city": "largo",
    "slug": "doctors-weight-loss-center-medical-spa-largo"
  },
  {
    "city": "largo",
    "slug": "hydrate-heal-by-heather-largo"
  },
  {
    "city": "largo",
    "slug": "interface-aesthetics-whitnie-padron-aprn-largo"
  },
  {
    "city": "largo",
    "slug": "massage-envy-largo"
  },
  {
    "city": "largo",
    "slug": "pigment-station-hair-salon-and-spa-largo"
  },
  {
    "city": "largo",
    "slug": "regen-and-restore-largo-fl"
  },
  {
    "city": "largo",
    "slug": "synskn-esthetics-largo"
  },
  {
    "city": "las-vegas",
    "slug": "advanced-aesthetics-centennial-las-vegas"
  },
  {
    "city": "las-vegas",
    "slug": "alena-medspa-las-vegas-by-alonso-medical-center-las-vegas"
  },
  {
    "city": "las-vegas",
    "slug": "alena-medspa-las-vegas-by-alonso-medical-center-las-vegas-nevada"
  },
  {
    "city": "las-vegas",
    "slug": "center-for-aesthetic-medicine-las-vegas-nv"
  },
  {
    "city": "las-vegas",
    "slug": "esti-co-las-vegas"
  },
  {
    "city": "las-vegas",
    "slug": "l-a-laser-skin-las-vegas-nevada"
  },
  {
    "city": "las-vegas",
    "slug": "laser-skin-lounge-las-vegas-nevada"
  },
  {
    "city": "las-vegas",
    "slug": "moderna-laser-med-spa-las-vegas-nevada"
  },
  {
    "city": "las-vegas",
    "slug": "nakedmd-med-spa-las-vegas-las-vegas-nevada"
  },
  {
    "city": "las-vegas",
    "slug": "semaglutide-online-las-vegas-nevada"
  },
  {
    "city": "lauderhill",
    "slug": "body-aesthetics-med-spa-lauderhill"
  },
  {
    "city": "lauderhill",
    "slug": "cure-spa-lauderhill"
  },
  {
    "city": "lauderhill",
    "slug": "envy-my-slay-lauderhill"
  },
  {
    "city": "lauderhill",
    "slug": "unica-beauty-salon-dominican-hair-salon-lauderhill"
  },
  {
    "city": "league-city",
    "slug": "renewed-radiance-med-spa-league-city-texas"
  },
  {
    "city": "leesburg",
    "slug": "ageless-beauty-med-spa-leesburg"
  },
  {
    "city": "leesburg",
    "slug": "elevate-health-medspa-gynecology-leesburg-leesburg"
  },
  {
    "city": "leesburg",
    "slug": "laser-hair-removal"
  },
  {
    "city": "leesburg",
    "slug": "ru-b-ess-spa-and-beauty-bar-leesburg"
  },
  {
    "city": "leesburg",
    "slug": "vip-spa-nails-leesburg"
  },
  {
    "city": "littleton",
    "slug": "colorado-body-sculpting-littleton-co"
  },
  {
    "city": "long-island-city",
    "slug": "bared-monkey-laser-spa-long-island-city-long-island-city"
  },
  {
    "city": "long-island-city",
    "slug": "bella-nyc-aesthetics-med-spa-long-island-city-ny"
  },
  {
    "city": "long-island-city",
    "slug": "diamond-works-medspa-long-island-city"
  },
  {
    "city": "long-island-city",
    "slug": "diamond-works-medspa-long-island-city-ny"
  },
  {
    "city": "long-island-city",
    "slug": "glowbar-long-island-city-long-island-city-ny"
  },
  {
    "city": "long-island-city",
    "slug": "just-glam-aesthetics-long-island-city"
  },
  {
    "city": "long-island-city",
    "slug": "laser-hair-removal"
  },
  {
    "city": "long-island-city",
    "slug": "nu-med-med-spa-integrative-wellness-garden-city-long-island-city"
  },
  {
    "city": "long-island-city",
    "slug": "weight-loss-ozempic"
  },
  {
    "city": "long-island-city",
    "slug": "yunara-life-moving-to-gramercy-june-2026-long-island-city-ny"
  },
  {
    "city": "los-angeles",
    "slug": "bright-medical-spa-los-angeles"
  },
  {
    "city": "los-angeles",
    "slug": "iv-glow-bar-los-angeles-california"
  },
  {
    "city": "los-angeles",
    "slug": "iv-therapy"
  },
  {
    "city": "los-angeles",
    "slug": "ive-medical-spa-los-angeles-california"
  },
  {
    "city": "los-angeles",
    "slug": "mega-iv-therapy-la-k-town-los-angeles-california"
  },
  {
    "city": "los-angeles",
    "slug": "rejuvenate-wellness-health-center-los-angeles-california"
  },
  {
    "city": "los-angeles",
    "slug": "skin-story-med-spa-los-angeles-california"
  },
  {
    "city": "lynnfield",
    "slug": "neem-medical-spa-lynnfield-lynnfield-massachusetts"
  },
  {
    "city": "lynnfield",
    "slug": "restore-hyper-wellness-lynnfield-massachusetts"
  },
  {
    "city": "maple-grove",
    "slug": "luxus-laser-and-esthetics-maple-grove-minnesota"
  },
  {
    "city": "marco-island",
    "slug": "cosmetic-skin-laser-center-marco-island"
  },
  {
    "city": "marco-island",
    "slug": "la-font-d-medspa-marco-island"
  },
  {
    "city": "marco-island",
    "slug": "peaceful-escapes-therapeutic-massage-marco-island-fl"
  },
  {
    "city": "marco-island",
    "slug": "renu-skin-wellness-medspa-marco-island-marco-island"
  },
  {
    "city": "marco-island",
    "slug": "spa-by-jw-at-jw-marriott-marco-island-marco-island"
  },
  {
    "city": "marco-island",
    "slug": "tender-touch-massage-marco-island"
  },
  {
    "city": "margate",
    "slug": "care-wellness-center-margate"
  },
  {
    "city": "margate",
    "slug": "lounge-hair-salon-margate"
  },
  {
    "city": "margate",
    "slug": "melaglo-skin-margate"
  },
  {
    "city": "margate",
    "slug": "rosana-s-hair-botox-center-dominican-hair-salon-margate"
  },
  {
    "city": "margate",
    "slug": "serenity-oasis-spa-fl-margate"
  },
  {
    "city": "margate",
    "slug": "threading-and-glow-by-faye-margate"
  },
  {
    "city": "margate",
    "slug": "vanessa-hair-style-margate"
  },
  {
    "city": "matthews",
    "slug": "premier-hormone-health-wellness-matthews-north-carolina"
  },
  {
    "city": "melbourne",
    "slug": "microneedling"
  },
  {
    "city": "melbourne",
    "slug": "the-refinery-medspa-wellness-melbourne-fl"
  },
  {
    "city": "melbourne",
    "slug": "weight-loss-ozempic"
  },
  {
    "city": "methuen",
    "slug": "ultimate-glow-llc-methuen-massachusetts"
  },
  {
    "city": "miami-beach",
    "slug": "body-contouring-wellness-studio-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "coolsculpting-elite-center-of-miami-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "dr-miami-beach-tarik-m-husain-md-facs-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "esthetics-by-natalia-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "hall-longevity-clinic-miami-beach-fl"
  },
  {
    "city": "miami-beach",
    "slug": "ject-miami-beach-fl"
  },
  {
    "city": "miami-beach",
    "slug": "laseraway-south-beach-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "life-extender-clinic-medspa-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "lorena-zuluaga-aesthetics-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "microneedling-miami-center-morpheus8-specialists-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "reviv-miami-beach-mobile-iv-therapy-miami-beach-fl"
  },
  {
    "city": "miami-beach",
    "slug": "skin-house-of-beauty-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "the-keloid-plastic-surgery-center-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "the-shape-spa-miami-beach"
  },
  {
    "city": "miami-beach",
    "slug": "utopia-image-miami-beach-fl"
  },
  {
    "city": "miami-beach",
    "slug": "vanity-aesthetics-inc-roderic-rettig-aprn-miami-beach"
  },
  {
    "city": "miami-gardens",
    "slug": "angie-s-aesthetic-miami-gardens"
  },
  {
    "city": "miami-gardens",
    "slug": "d-k-nails-miami-gardens"
  },
  {
    "city": "miami-gardens",
    "slug": "g-nails-spa-ii-miami-gardens"
  },
  {
    "city": "miami-gardens",
    "slug": "impact-glamour-med-spa-lashes-brows-miami-gardens-fl"
  },
  {
    "city": "miami-gardens",
    "slug": "mg-cosmetic-center-miami-gardens"
  },
  {
    "city": "miami-gardens",
    "slug": "miamibrowboss-llc-miami-gardens"
  },
  {
    "city": "miami-gardens",
    "slug": "yoly-dominican-salon-miami-gardens"
  },
  {
    "city": "miami-lakes",
    "slug": "auren-med-spa-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "chinitas-beauty-miami-lakes-fl"
  },
  {
    "city": "miami-lakes",
    "slug": "dermatology-of-miami-previously-dr-kenneth-rosen-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "family-dentistry-orthodontics-of-miami-lakes-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "harmony-cosmetic-center-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "medspa-africacuzan-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "miami-lakes-med-spa-miami-lakes-fl"
  },
  {
    "city": "miami-lakes",
    "slug": "new-care-medical-wellness-group-miami-lakes-fl"
  },
  {
    "city": "miami-lakes",
    "slug": "palmetto-smile-center-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "paris-medical-spa-miami-lakes-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "waltcare-clinic-miami-lakes"
  },
  {
    "city": "miami-lakes",
    "slug": "xcellence-wellness-and-aesthetics-miami-lakes"
  },
  {
    "city": "miami",
    "slug": "4ever-young-med-spa-wellness-center-miami-dadeland-miami"
  },
  {
    "city": "miami",
    "slug": "b2h-medical-laser-llc-miami"
  },
  {
    "city": "miami",
    "slug": "face-and-body-concept-miami-fl"
  },
  {
    "city": "miami",
    "slug": "healing-touch-nails-boutique-and-medspa-miami"
  },
  {
    "city": "miami",
    "slug": "hempire-spa-miami"
  },
  {
    "city": "miami",
    "slug": "laser-hair-removal"
  },
  {
    "city": "miami",
    "slug": "lely-enhanced-medicine-aesthetics-miami"
  },
  {
    "city": "miami",
    "slug": "miami-skin-tightening-and-fat-reduction-miami"
  },
  {
    "city": "miami",
    "slug": "mm-medspa-laser-center-miami-fl"
  },
  {
    "city": "miami",
    "slug": "nutrici-n-vida-y-belleza-corp-miami"
  },
  {
    "city": "miami",
    "slug": "paris-medical-spa-kendall-miami"
  },
  {
    "city": "miami",
    "slug": "serenity-medical-spa-miami"
  },
  {
    "city": "miami",
    "slug": "soji-medspa-miami"
  },
  {
    "city": "miami",
    "slug": "white-coat-glam-llc-miami"
  },
  {
    "city": "minneapolis",
    "slug": "drip-refresh-mobile-iv-therapy-minneapolis-minneapolis-minnesota"
  },
  {
    "city": "minneapolis",
    "slug": "laser-hair-removal"
  },
  {
    "city": "minneapolis",
    "slug": "magnolia-aesthetics-wellness-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "michelle-aesthetics-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "michelle-aesthetics-minneapolis-minnesota"
  },
  {
    "city": "minneapolis",
    "slug": "minneapolis-anti-aging-skin-clinic-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "muse-aesthetics-co-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "nostalgia-aesthetics-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "rachel-dahlen-aesthetics-edina-botox-juvederm-minneapolis-mn"
  },
  {
    "city": "minneapolis",
    "slug": "renew-med-spa-plus-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "sev-laser-minneapolis-minnesota"
  },
  {
    "city": "minneapolis",
    "slug": "skin-artisans-at-edina-plastic-surgery-minneapolis"
  },
  {
    "city": "minneapolis",
    "slug": "skin-artisans-minnetonka-minneapolis-minnesota"
  },
  {
    "city": "minneapolis",
    "slug": "the-skin-scene-aesthetics-minneapolis"
  },
  {
    "city": "miramar",
    "slug": "pphw-primary-care-wellnesss-miramar"
  },
  {
    "city": "miramar",
    "slug": "rebounce-iv-health-and-wellness-miramar"
  },
  {
    "city": "miramar",
    "slug": "sedation-dental-spa-of-miramar-miramar"
  },
  {
    "city": "miramar",
    "slug": "zobia-health-aesthetics-miramar"
  },
  {
    "city": "naples",
    "slug": "5th-avenue-spa-naples"
  },
  {
    "city": "naples",
    "slug": "advanced-skincare-laser-by-jessica-naples"
  },
  {
    "city": "naples",
    "slug": "aesthetic-health-naples-naples"
  },
  {
    "city": "naples",
    "slug": "aesthetic-justice-by-chrissy-taylor-naples"
  },
  {
    "city": "naples",
    "slug": "aesthetique-naples"
  },
  {
    "city": "naples",
    "slug": "anavaya-med-spa-naples"
  },
  {
    "city": "naples",
    "slug": "chemical-peels"
  },
  {
    "city": "naples",
    "slug": "dna-wellness-and-longevity-institute-naples"
  },
  {
    "city": "naples",
    "slug": "dr-irina-toma-aesthetics-naples"
  },
  {
    "city": "naples",
    "slug": "fifth-avenue-wax-center-and-spa-naples"
  },
  {
    "city": "naples",
    "slug": "gs-med-spa-naples"
  },
  {
    "city": "naples",
    "slug": "jewell-medical-spa-mr-injectable-naples-fl"
  },
  {
    "city": "naples",
    "slug": "joli-visage-naples-naples"
  },
  {
    "city": "naples",
    "slug": "m-d-laser-aesthetics-naples"
  },
  {
    "city": "naples",
    "slug": "med-spa-on-5th-naples"
  },
  {
    "city": "naples",
    "slug": "meridian-medical-spa-naples"
  },
  {
    "city": "naples",
    "slug": "naples-facial-botox-med-spa-naples"
  },
  {
    "city": "naples",
    "slug": "naples-facial-botox-med-spa-naples-fl"
  },
  {
    "city": "naples",
    "slug": "naples-laser-skin-aesthetics-naples-fl"
  },
  {
    "city": "naples",
    "slug": "naples-non-surgical-body-sculpting-naples-fl"
  },
  {
    "city": "naples",
    "slug": "one-place-wellness-naples"
  },
  {
    "city": "naples",
    "slug": "optimal-wellness-naples"
  },
  {
    "city": "naples",
    "slug": "prime-iv-hydration-wellness-central-naples-naples"
  },
  {
    "city": "naples",
    "slug": "purpose-advanced-esthetics-naples"
  },
  {
    "city": "naples",
    "slug": "skinco-naples-naples"
  },
  {
    "city": "naples",
    "slug": "victory-wellness-med-spa-of-naples-naples"
  },
  {
    "city": "naples",
    "slug": "von-co-medical-aesthetics-studio-naples"
  },
  {
    "city": "nashville",
    "slug": "am-lie-aesthetics-and-wellness-nashville-tn"
  },
  {
    "city": "nashville",
    "slug": "botox-fillers"
  },
  {
    "city": "nashville",
    "slug": "coolsculpting"
  },
  {
    "city": "nashville",
    "slug": "hi-finch-nashville-tennessee"
  },
  {
    "city": "nashville",
    "slug": "iv-therapy"
  },
  {
    "city": "nashville",
    "slug": "laser-hair-removal"
  },
  {
    "city": "nashville",
    "slug": "microneedling"
  },
  {
    "city": "nashville",
    "slug": "nashville-cosmetic-surgery-the-skin-lounge-nashville-tn"
  },
  {
    "city": "nashville",
    "slug": "revive-aesthetics-nashville-nashville-tennessee"
  },
  {
    "city": "nashville",
    "slug": "revive-aesthetics-nashville-nashville-tn"
  },
  {
    "city": "nashville",
    "slug": "the-drip-lab-mobile-iv-hydration-nashville-nashville-tennessee"
  },
  {
    "city": "nashville",
    "slug": "weight-loss-ozempic"
  },
  {
    "city": "new-port-richey",
    "slug": "beauty-lab-new-port-richey"
  },
  {
    "city": "new-port-richey",
    "slug": "dragonfly-aesthetics-new-port-richey"
  },
  {
    "city": "new-york-city",
    "slug": "aestheticsmd-by-jean-rhee-upper-east-side-new-york-city"
  },
  {
    "city": "new-york-city",
    "slug": "alynemd-nyc-new-york-city"
  },
  {
    "city": "new-york-city",
    "slug": "elite-aesthetics-new-york-city"
  },
  {
    "city": "new-york-city",
    "slug": "esthetic-lab-nyc-new-york-city"
  },
  {
    "city": "new-york",
    "slug": "alynemd-nyc-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "art-and-anatomy-medical-spa-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "beautyfix-medspa-flatiron-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "berejuved-medical-spa-wellness-studio-nyc-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "ever-body-flatiron-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "iv-therapy-and-nad-nyc-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "le-clinique-nyc-laser-hair-removal-new-york-ny"
  },
  {
    "city": "new-york",
    "slug": "microneedling-nyc-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "morpheus-8-treatment-nyc-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "nad-iv-therapy-nyc-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "sienna-lilly-aesthetics-new-york-new-york"
  },
  {
    "city": "new-york",
    "slug": "the-dripbar-times-square-at-alter-native-wellness-new-york-new-york"
  },
  {
    "city": "newport-beach",
    "slug": "aesthetic-lounge-newport-beach"
  },
  {
    "city": "newport-beach",
    "slug": "alchemy-43-newport-beach-newport-beach"
  },
  {
    "city": "newport-beach",
    "slug": "coolsculpting"
  },
  {
    "city": "newport-beach",
    "slug": "microneedling"
  },
  {
    "city": "newport-beach",
    "slug": "newport-beach-medspa-newport-beach"
  },
  {
    "city": "newport-beach",
    "slug": "pure-beauty-skin-care-newport-beach"
  },
  {
    "city": "newport-beach",
    "slug": "the-retreat-wellness-aesthetics-newport-beach"
  },
  {
    "city": "newport-beach",
    "slug": "the-treatment-skin-boutique-newport-beach-newport-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "aesthetic-clinic-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "alejandra-moros-med-spa-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "all-asian-massage-6-dba-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "cristina-beauty-salon-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "marra-s-beauty-bar-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "medstation-sunny-isles-cl-nica-m-dica-em-sunny-isles-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "red-rose-cosmetic-and-surgical-arts-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "seissa-belmondo-beauty-spa-north-miami-beach"
  },
  {
    "city": "north-miami-beach",
    "slug": "summer-plastic-surgery-north-miami-beach"
  },
  {
    "city": "north-miami",
    "slug": "alejandra-moros-med-spa-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "alexis-lauren-bay-harbor-islands-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "bosley-hair-restoration-transplant-miami-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "del-campo-dermatology-laser-institute-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "emsculpt-neo-body-contouring-treatment-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "glotique-by-lyf-aesthetics-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "jannelle-s-naked-face-medspa-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "medstation-sunny-isles-cl-nica-m-dica-em-sunny-isles-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "mint-esthetics-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "one-touch-body-contour-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "pler-clinics-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "pler-clinics-north-miami-fl"
  },
  {
    "city": "north-miami",
    "slug": "tillys-wellness-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "true-you-aesthetics-north-miami"
  },
  {
    "city": "north-miami",
    "slug": "urological-consultants-of-florida-north-miami-fl"
  },
  {
    "city": "ocala",
    "slug": "advance-wellness-aesthetics-of-ocala-ocala"
  },
  {
    "city": "ocala",
    "slug": "advanced-wellness-infusion-centers-llc-ocala"
  },
  {
    "city": "ocala",
    "slug": "aqua-med-spa-ocala-location-ocala"
  },
  {
    "city": "ocala",
    "slug": "clark-co-wellness-spa-ocala"
  },
  {
    "city": "ocala",
    "slug": "luxury-medical-estheticians-ocala"
  },
  {
    "city": "ocala",
    "slug": "med-spa-ocala"
  },
  {
    "city": "ocala",
    "slug": "naturally-rae-aesthetics-wellness-ocala"
  },
  {
    "city": "ocala",
    "slug": "the-fix-aesthetic-clinic-ocala"
  },
  {
    "city": "ocala",
    "slug": "u-skin-aesthetics-ocala-fl-ocala"
  },
  {
    "city": "orange-park",
    "slug": "deleon-wellness-medical-center-orange-park-fl"
  },
  {
    "city": "orange-park",
    "slug": "natural-body-wellness-clinic-orange-park-fl"
  },
  {
    "city": "orlando",
    "slug": "hydrafacial"
  },
  {
    "city": "orlando",
    "slug": "laser-hair-removal"
  },
  {
    "city": "oviedo",
    "slug": "enora-wellness-and-aesthetics-medical-spa-and-weight-loss-clinic-oviedo"
  },
  {
    "city": "oviedo",
    "slug": "fluid-med-spa-weight-loss-oviedo-fl-oviedo"
  },
  {
    "city": "oviedo",
    "slug": "leland-esthetics-dayspa-oviedo"
  },
  {
    "city": "oviedo",
    "slug": "oviedo-med-spa-oviedo"
  },
  {
    "city": "palm-bay",
    "slug": "hand-stone-massage-and-facial-spa-palm-bay"
  },
  {
    "city": "palm-bay",
    "slug": "hand-stone-massage-and-facial-spa-palm-bay-fl"
  },
  {
    "city": "palm-bay",
    "slug": "mila-massage-spa-palm-bay"
  },
  {
    "city": "palm-beach-gardens",
    "slug": "estetica-institute-of-the-palm-beaches-palm-beach-gardens-fl"
  },
  {
    "city": "palm-beach-gardens",
    "slug": "hamilton-aesthetics-palm-beach-gardens-fl"
  },
  {
    "city": "palm-beach-gardens",
    "slug": "new-radiance-cosmetic-centers-palm-beach-gardens-fl"
  },
  {
    "city": "palm-beach-gardens",
    "slug": "respa-palm-beach-palm-beach-gardens-fl"
  },
  {
    "city": "palm-beach-gardens",
    "slug": "the-lane-spa-palm-beach-gardens-fl"
  },
  {
    "city": "panama-city",
    "slug": "aqua-medical-spa-panama-city-panama-city"
  },
  {
    "city": "panama-city",
    "slug": "bayview-wellness-aesthetics-panama-city"
  },
  {
    "city": "panama-city",
    "slug": "glam-glo-medical-aesthetics-lounge-llc-panama-city"
  },
  {
    "city": "panama-city",
    "slug": "nation-s-best-aesthetics-wellness-panama-city"
  },
  {
    "city": "panama-city",
    "slug": "southern-serenity-co-panama-city"
  },
  {
    "city": "panama-city",
    "slug": "the-art-of-skin-institute-of-aesthetics-panama-city-fl"
  },
  {
    "city": "parkland",
    "slug": "flow-iv-wellness-parkland-parkland"
  },
  {
    "city": "pembroke-pines",
    "slug": "coolsculpting"
  },
  {
    "city": "pensacola",
    "slug": "microneedling"
  },
  {
    "city": "philadelphia",
    "slug": "bella-medspa-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "body-beauty-lab-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "glow-lab-medspa-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "meesha-aesthetics-in-philly-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "peptide-therapy"
  },
  {
    "city": "philadelphia",
    "slug": "phillymedclub-philadelphia-pa"
  },
  {
    "city": "philadelphia",
    "slug": "revive-medical-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "serenity-aesthetics-wellness-pllc-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "skin-retreat-medspa-philadelphia-pennsylvania"
  },
  {
    "city": "philadelphia",
    "slug": "soft-touch-aesthetics-philadelphia"
  },
  {
    "city": "phoenix",
    "slug": "az-medical-weight-control-phoenix-phoenix-arizona"
  },
  {
    "city": "phoenix",
    "slug": "it-s-a-secret-med-spa-phoenix-phoenix"
  },
  {
    "city": "phoenix",
    "slug": "laseraway-phoenix-phoenix-arizona"
  },
  {
    "city": "phoenix",
    "slug": "nakedmd-med-spa-phoenix-phoenix-arizona"
  },
  {
    "city": "phoenix",
    "slug": "red-mountain-weight-loss-phoenix-arizona"
  },
  {
    "city": "phoenix",
    "slug": "saguaro-medical-weight-control-semaglutide-phentermine-phoenix-arizona"
  },
  {
    "city": "phoenix",
    "slug": "skin-and-face-phoenix-phoenix"
  },
  {
    "city": "phoenix",
    "slug": "suddenly-slimmer-med-spa-phoenix"
  },
  {
    "city": "phoenix",
    "slug": "touch-advanced-aesthetics-phoenix-arizona"
  },
  {
    "city": "phoenix",
    "slug": "valley-medical-weight-loss-phoenix-phoenix-arizona"
  },
  {
    "city": "pinecrest",
    "slug": "iv-therapy"
  },
  {
    "city": "pinecrest",
    "slug": "lesly-sol-beauty-spa-pinecrest"
  },
  {
    "city": "pinecrest",
    "slug": "skin-med-spa-pinecrest"
  },
  {
    "city": "pinecrest",
    "slug": "skin-med-spa-pinecrest-fl"
  },
  {
    "city": "pinecrest",
    "slug": "skin-plus-beauty-pinecrest"
  },
  {
    "city": "pinecrest",
    "slug": "skin-plus-beauty-pinecrest-fl"
  },
  {
    "city": "pinecrest",
    "slug": "trt-testosterone"
  },
  {
    "city": "pinecrest",
    "slug": "vive-weight-loss-center-pinecrest"
  },
  {
    "city": "pinellas-park",
    "slug": "ever-gorgeous-beauty-spa-pinellas-park"
  },
  {
    "city": "pinellas-park",
    "slug": "hess-spinal-medical-centers-pinellas-park"
  },
  {
    "city": "pinellas-park",
    "slug": "pine-tree-massage-spa-pinellas-park"
  },
  {
    "city": "pinellas-park",
    "slug": "soothing-stone-massage-pinellas-park"
  },
  {
    "city": "pinellas-park",
    "slug": "veda-aesthetic-healthcare-pinellas-park"
  },
  {
    "city": "plano",
    "slug": "aesthetic-collective-plano-plano"
  },
  {
    "city": "plano",
    "slug": "laser-hair-removal"
  },
  {
    "city": "plano",
    "slug": "princess-med-spa-plano"
  },
  {
    "city": "plano",
    "slug": "raven-med-spa-plano"
  },
  {
    "city": "plano",
    "slug": "revived-aesthetics-plano"
  },
  {
    "city": "plantation",
    "slug": "refresh-fort-lauderdale-medical-aesthetics-formerly-xs-medspa-plantation-fl"
  },
  {
    "city": "pompano-beach",
    "slug": "age-well-dr-pompano-affordable-testosterone-suboxone-ketamine-semaglutide-tirzepatide-lab-work-stem-cells-prp-pompano-beach"
  },
  {
    "city": "pompano-beach",
    "slug": "beach-body-medspa-pompano-beach"
  },
  {
    "city": "pompano-beach",
    "slug": "beauty-in-everything-medspa-pompano-beach"
  },
  {
    "city": "pompano-beach",
    "slug": "botox-fillers"
  },
  {
    "city": "pompano-beach",
    "slug": "coolsculpting"
  },
  {
    "city": "pompano-beach",
    "slug": "get-waisted-by-lexi-post-op-lymphatic-massage-body-contouring-pompano-beach"
  },
  {
    "city": "pompano-beach",
    "slug": "premier-medical-spa-aesthetics-pompano-beach-fl"
  },
  {
    "city": "pompano-beach",
    "slug": "the-sandbar-beauty-company-pompano-beach"
  },
  {
    "city": "pompano-beach",
    "slug": "zen-health-and-beauty-pompano-beach"
  },
  {
    "city": "ponte-vedra-beach",
    "slug": "contoura-facial-plastic-surgery-ponte-vedra-beach"
  },
  {
    "city": "ponte-vedra-beach",
    "slug": "cosmetic-gynecology-florida-ponte-vedra-beach"
  },
  {
    "city": "ponte-vedra-beach",
    "slug": "cosmetic-gynecology-florida-ponte-vedra-beach-fl"
  },
  {
    "city": "ponte-vedra-beach",
    "slug": "dynamic3-health-ponte-vedra-beach"
  },
  {
    "city": "ponte-vedra-beach",
    "slug": "florida-facelift-skin-cancer-center-ponte-vedra-beach"
  },
  {
    "city": "ponte-vedra-beach",
    "slug": "ponte-vedra-plastic-surgery-annex-location-ponte-vedra-beach"
  },
  {
    "city": "port-st-lucie",
    "slug": "relive-tradition-port-st-lucie-fl"
  },
  {
    "city": "portland",
    "slug": "art-of-injectables-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "aura-aesthetics-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "full-potential-hrt-clinic-testosterone-hrt-beyond-portland-or-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "health-plus-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "lumera-regenerative-medicine-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "md-beauty-lab-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "optifit-medical-weight-loss-wellness-clinic-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "pearl-medspa-portland-oregon"
  },
  {
    "city": "portland",
    "slug": "portland-s-coolsculpting-clinic-portland-oregon"
  },
  {
    "city": "punta-gorda",
    "slug": "bare-beauty-bar-punta-gorda"
  },
  {
    "city": "punta-gorda",
    "slug": "face-it-botox-bar-aesthetics-wellness-punta-gorda-punta-gorda"
  },
  {
    "city": "punta-gorda",
    "slug": "florida-skin-center-punta-gorda"
  },
  {
    "city": "punta-gorda",
    "slug": "red-light-therapy-diana-s-cutting-edge-salon-boutique-punta-gorda"
  },
  {
    "city": "punta-gorda",
    "slug": "sculpt-slim-wellness-punta-gorda"
  },
  {
    "city": "riverview",
    "slug": "beaulight-wh-riverview"
  },
  {
    "city": "riverview",
    "slug": "duque-spa-riverview"
  },
  {
    "city": "riverview",
    "slug": "riverview-dental-arts-riverview"
  },
  {
    "city": "riverview",
    "slug": "sophia-skin-spa-riverview"
  },
  {
    "city": "riverview",
    "slug": "you-glow-aesthetics-tampa-riverview"
  },
  {
    "city": "riviera-beach",
    "slug": "dr-jose-a-navarro-md-riviera-beach"
  },
  {
    "city": "san-antonio",
    "slug": "alamo-sculpting-wellness-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "body-concepts-aesthetic-wellness-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "esthetica-medspa-san-antonio-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "it-s-a-secret-med-spa-san-antonio"
  },
  {
    "city": "san-antonio",
    "slug": "laseraway-san-antonio-quarry-village-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "lift-and-revive-aesthetics-and-wellness-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "lumyn-medspa-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "nakedmd-med-spa-san-antonio-san-antonio"
  },
  {
    "city": "san-antonio",
    "slug": "nakedmd-med-spa-san-antonio-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "radiant-heights-med-spa-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "san-antonio-med-spa-san-antonio"
  },
  {
    "city": "san-antonio",
    "slug": "sculpted-md-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "texas-dermatology-med-spa-san-antonio-texas"
  },
  {
    "city": "san-antonio",
    "slug": "vita-nova-anti-aging-and-rejuvenation-center-san-antonio-texas"
  },
  {
    "city": "san-diego",
    "slug": "aloderma-med-spa-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "avalon-laser-san-diego-botox-clinic-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "dermacare-medical-aesthetics-rancho-bernardo-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "domus-vitae-gabriel-gonzalez-bsn-rn-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "emagine-med-spa-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "evolve-medical-services-pc-san-diego-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "ithrivemd-of-mission-valley-san-diego-california"
  },
  {
    "city": "san-diego",
    "slug": "laser-hair-removal"
  },
  {
    "city": "san-diego",
    "slug": "olive-medical-aesthetic-center-san-diego-san-diego-ca"
  },
  {
    "city": "san-diego",
    "slug": "sdbotox-pacific-beach-san-diego-ca"
  },
  {
    "city": "san-diego",
    "slug": "skin-medical-spa-in-san-diego-skin-tightening-cryo-fat-freezing-lipo-cavitation-san-diego-ca"
  },
  {
    "city": "san-diego",
    "slug": "skyy-med-spa-san-diego"
  },
  {
    "city": "san-francisco",
    "slug": "coolsculpting"
  },
  {
    "city": "san-francisco",
    "slug": "hayes-valley-medical-esthetics-cow-hollow-marina-san-francisco"
  },
  {
    "city": "san-francisco",
    "slug": "iv-therapy"
  },
  {
    "city": "san-francisco",
    "slug": "medspa-of-san-francisco-san-francisco"
  },
  {
    "city": "san-francisco",
    "slug": "microneedling"
  },
  {
    "city": "san-francisco",
    "slug": "nob-hill-aesthetics-medical-spa-san-francisco"
  },
  {
    "city": "san-francisco",
    "slug": "nob-hill-aesthetics-medical-spa-san-francisco-ca"
  },
  {
    "city": "sandy-springs",
    "slug": "bodenvy-coolsculpting-weight-loss-body-sculpting-atlanta-sandy-springs-georgia"
  },
  {
    "city": "sanford",
    "slug": "belle-ame-wellness-sanford"
  },
  {
    "city": "sanford",
    "slug": "coast-to-coast-wellness-and-aesthetics-sanford-fl"
  },
  {
    "city": "sanford",
    "slug": "elite-aesthetics-skin-wellness-center-sanford"
  },
  {
    "city": "sanford",
    "slug": "newgen-direct-primary-care-sanford"
  },
  {
    "city": "sanford",
    "slug": "sage-wellness-center-acupuncture-herbs-sanford"
  },
  {
    "city": "santa-monica",
    "slug": "santa-monica-medical-aesthetics-santa-monica"
  },
  {
    "city": "santa-monica",
    "slug": "skin-remedies-santa-monica"
  },
  {
    "city": "sarasota",
    "slug": "botox-fillers"
  },
  {
    "city": "sarasota",
    "slug": "hydrafacial"
  },
  {
    "city": "sarasota",
    "slug": "laser-hair-removal"
  },
  {
    "city": "sarasota",
    "slug": "microneedling"
  },
  {
    "city": "scottsdale",
    "slug": "botox-fillers"
  },
  {
    "city": "scottsdale",
    "slug": "franco-wellness-aesthetics-scottsdale-az-scottsdale"
  },
  {
    "city": "scottsdale",
    "slug": "hydrafacial-and-chemical-peels-by-kapri-skin-scottsdale-arizona"
  },
  {
    "city": "scottsdale",
    "slug": "institute-of-aesthetics-beauty-wellness-scottsdale-az"
  },
  {
    "city": "scottsdale",
    "slug": "laser-hair-removal"
  },
  {
    "city": "scottsdale",
    "slug": "microneedling"
  },
  {
    "city": "scottsdale",
    "slug": "moderne-medical-aesthetics-scottsdale"
  },
  {
    "city": "scottsdale",
    "slug": "scottsdale-med-spa-scottsdale"
  },
  {
    "city": "scottsdale",
    "slug": "skin-savvy-aesthetics-med-spa-scottsdale"
  },
  {
    "city": "scottsdale",
    "slug": "the-perfect-secret-med-spa-scottsdale"
  },
  {
    "city": "seattle",
    "slug": "maintenance-bar-seattle-washington"
  },
  {
    "city": "seattle",
    "slug": "microneedling"
  },
  {
    "city": "seattle",
    "slug": "pinch-med-spa-seattle-concierge-mobile-at-home-botox-microneedling-chemical-peels-seattle"
  },
  {
    "city": "seattle",
    "slug": "pinch-med-spa-seattle-concierge-mobile-at-home-botox-microneedling-chemical-peels-seattle-wa"
  },
  {
    "city": "seattle",
    "slug": "seattle-aesthetic-injector-med-spa-seattle"
  },
  {
    "city": "seattle",
    "slug": "skinspirit-seattle-university-village-seattle"
  },
  {
    "city": "south-windsor",
    "slug": "kalologie-club-studio-south-windsor-south-windsor-connecticut"
  },
  {
    "city": "spring-hill",
    "slug": "ameli-wellness-medspa-spring-hill"
  },
  {
    "city": "spring-hill",
    "slug": "drip-n-fit-iv-hydration-and-wellness-spring-hill"
  },
  {
    "city": "spring-hill",
    "slug": "so-aesthetic-medical-and-wellness-spring-hill"
  },
  {
    "city": "spring-hill",
    "slug": "the-red-room-salon-and-day-spa-spring-hill-fl"
  },
  {
    "city": "spring-valley",
    "slug": "sd-weight-loss-center-spring-valley-california"
  },
  {
    "city": "st-augustine",
    "slug": "alchemy-wellness-st-augustine"
  },
  {
    "city": "st-augustine",
    "slug": "amason-aesthetics-st-augustine"
  },
  {
    "city": "st-augustine",
    "slug": "coastal-radiance-aesthetics-st-augustine"
  },
  {
    "city": "st-augustine",
    "slug": "crescent-beach-care-us1-st-augustine"
  },
  {
    "city": "st-augustine",
    "slug": "lacura-salt-spa-st-augustine"
  },
  {
    "city": "st-augustine",
    "slug": "the-pretty-bohemian-st-augustine"
  },
  {
    "city": "st-petersburg",
    "slug": "glow-st-pete-med-spa-st-petersburg-fl"
  },
  {
    "city": "st-petersburg",
    "slug": "goldfingers-aesthetics-st-petersburg-st-petersburg-fl"
  },
  {
    "city": "st-petersburg",
    "slug": "indulgence-medical-day-spa-st-petersburg-fl"
  },
  {
    "city": "st-petersburg",
    "slug": "st-pete-aesthetics-the-medical-spa-experts-st-petersburg"
  },
  {
    "city": "st-petersburg",
    "slug": "st-pete-wellness-medspa-st-petersburg-fl"
  },
  {
    "city": "stuart",
    "slug": "advanced-diagnostic-group-beaches-mri-stuart"
  },
  {
    "city": "stuart",
    "slug": "glow-odyssey-stuart"
  },
  {
    "city": "stuart",
    "slug": "lumi-re-by-wellspring-medical-solution-stuart"
  },
  {
    "city": "stuart",
    "slug": "mckay-dermatology-medspa-stuart"
  },
  {
    "city": "stuart",
    "slug": "neurostrive-stuart"
  },
  {
    "city": "stuart",
    "slug": "point-of-care-acupuncture-located-in-oasis-med-spa-stuart-fl"
  },
  {
    "city": "stuart",
    "slug": "pure-rejuvenation-anti-aging-stuart"
  },
  {
    "city": "stuart",
    "slug": "relive-health-stuart"
  },
  {
    "city": "stuart",
    "slug": "touch-of-beauty-by-megan-stuart"
  },
  {
    "city": "stuart",
    "slug": "vera-medical-stuart"
  },
  {
    "city": "stuart",
    "slug": "vera-medical-stuart-fl"
  },
  {
    "city": "stuart",
    "slug": "weight-loss-ozempic"
  },
  {
    "city": "sunrise",
    "slug": "360-radiance-sunrise"
  },
  {
    "city": "sunrise",
    "slug": "archetype-aesthetics-sunrise"
  },
  {
    "city": "sunrise",
    "slug": "cor-medical-centers-sunrise"
  },
  {
    "city": "sunrise",
    "slug": "dolce-medical-spa-sunrise-facials-skin-tightening-microneedling-sunrise"
  },
  {
    "city": "sunrise",
    "slug": "goddess-skin-care-sunrise"
  },
  {
    "city": "sunrise",
    "slug": "js-advanced-aesthetics-sunrise"
  },
  {
    "city": "sunrise",
    "slug": "revitacute-home-spa-sunrise"
  },
  {
    "city": "surfside",
    "slug": "iv-intuit-surfside"
  },
  {
    "city": "surfside",
    "slug": "northern-grace-medical-spa-surfside"
  },
  {
    "city": "surfside",
    "slug": "skin-institute-of-aesthetics-wellness-and-concierge-surfside"
  },
  {
    "city": "tallahassee",
    "slug": "botox-fillers"
  },
  {
    "city": "tamarac",
    "slug": "best-choice-wellness-aesthetics-tamarac"
  },
  {
    "city": "tamarac",
    "slug": "beu-medical-spa-tamarac"
  },
  {
    "city": "tamarac",
    "slug": "dr-martin-s-wellness-center-dr-real-j-martin-md-tamarac"
  },
  {
    "city": "tamarac",
    "slug": "drharris-md-weight-loss-clinic-tamarac-fl"
  },
  {
    "city": "tamarac",
    "slug": "heavenly-glow-aesthetics-tamarac"
  },
  {
    "city": "tamarac",
    "slug": "hong-hong-spa-tamarac"
  },
  {
    "city": "tamarac",
    "slug": "kenida-s-salon-tamarac"
  },
  {
    "city": "tamarac",
    "slug": "silhouette-hair-by-wendy-ny-domincan-stylist-tamarac"
  },
  {
    "city": "tampa",
    "slug": "chemical-peels"
  },
  {
    "city": "tampa",
    "slug": "coolsculpting"
  },
  {
    "city": "tampa",
    "slug": "forever-young-aesthetics-tampa-tampa-fl"
  },
  {
    "city": "tampa",
    "slug": "hydrafacial"
  },
  {
    "city": "tampa",
    "slug": "laser-hair-removal"
  },
  {
    "city": "tampa",
    "slug": "lineless-aesthetics-south-tampa-injectables-studio-tampa-fl"
  },
  {
    "city": "tampa",
    "slug": "peptide-therapy"
  },
  {
    "city": "tampa",
    "slug": "refresh-tampa-medical-aesthetics-formerly-ideal-image-tampa-fl"
  },
  {
    "city": "tarpon-springs",
    "slug": "cornerstone-wellness-center-tarpon-springs"
  },
  {
    "city": "tarpon-springs",
    "slug": "essential-esthetics-by-lindsey-tarpon-springs"
  },
  {
    "city": "tarpon-springs",
    "slug": "glow-and-grace-aesthetics-tarpon-springs"
  },
  {
    "city": "tarpon-springs",
    "slug": "miss-hua-s-massage-spa-crystal-river-tarpon-springs"
  },
  {
    "city": "tempe",
    "slug": "beautiful-aesthetics-az-tempe"
  },
  {
    "city": "tempe",
    "slug": "elite-medical-aesthetics-tempe"
  },
  {
    "city": "tempe",
    "slug": "hydrafacial"
  },
  {
    "city": "tempe",
    "slug": "microneedling"
  },
  {
    "city": "tempe",
    "slug": "perfect-skin-center-tempe"
  },
  {
    "city": "tempe",
    "slug": "valley-medical-weight-loss-tempe-tempe-arizona"
  },
  {
    "city": "tempe",
    "slug": "weight-loss-ozempic"
  },
  {
    "city": "the-villages",
    "slug": "amos-medspa-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "aqua-med-spa-the-villages-location-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "executive-skin-and-laser-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "face-2-face-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "holistic-skincare-wellness-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "infinity-medical-institute-at-the-villages-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "lymphatic-drainage-massage-clinic-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "medi-weightloss-wildwood-the-villages-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "metabolic-research-center-the-villages-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "metabolic-research-center-the-villages-the-villages-fl"
  },
  {
    "city": "the-villages",
    "slug": "michael-j-freeman-md-pa-the-villages"
  },
  {
    "city": "the-villages",
    "slug": "microneedling"
  },
  {
    "city": "the-villages",
    "slug": "sozo-wellness-center-the-villages"
  },
  {
    "city": "titusville",
    "slug": "florida-dermatology-associates-titusville"
  },
  {
    "city": "titusville",
    "slug": "indian-river-massage-titusville"
  },
  {
    "city": "titusville",
    "slug": "jacksonville-fl-botox-titusville"
  },
  {
    "city": "titusville",
    "slug": "skinderella-aesthetics-titusville"
  },
  {
    "city": "titusville",
    "slug": "water-s-edge-dermatology-titusville-titusville"
  },
  {
    "city": "tualatin",
    "slug": "prime-iv-hydration-wellness-tualatin-or-tualatin-oregon"
  },
  {
    "city": "vero-beach",
    "slug": "albany-aesthetics-vero-beach"
  },
  {
    "city": "vero-beach",
    "slug": "botox-fillers"
  },
  {
    "city": "vero-beach",
    "slug": "coolsculpting"
  },
  {
    "city": "vero-beach",
    "slug": "energy-spa-tanning-vero-beach"
  },
  {
    "city": "vero-beach",
    "slug": "laser-hair-removal"
  },
  {
    "city": "vero-beach",
    "slug": "peptide-therapy"
  },
  {
    "city": "vero-beach",
    "slug": "rise-modern-wellness-vero-beach"
  },
  {
    "city": "vero-beach",
    "slug": "white-pearl-spa-vero-beach"
  },
  {
    "city": "washington",
    "slug": "district-beautox-washington-district-of-columbia"
  },
  {
    "city": "washington",
    "slug": "it-s-a-secret-med-spa-washington-dc-washington-district-of-columbia"
  },
  {
    "city": "washington",
    "slug": "resculpt-aesthetics-washington-district-of-columbia"
  },
  {
    "city": "washington",
    "slug": "s-p-medspa-washington-district-of-columbia"
  },
  {
    "city": "washington",
    "slug": "skin-in-the-game-dc-washington-district-of-columbia"
  },
  {
    "city": "watertown",
    "slug": "skn-wtr-aesthetics-watertown-massachusetts"
  },
  {
    "city": "wellesley",
    "slug": "age-perfectly-wellesley-massachusetts"
  },
  {
    "city": "wellesley",
    "slug": "gfacemd-medical-spa-wellesley-wellesley-massachusetts"
  },
  {
    "city": "wellington",
    "slug": "aqua-restore-wellness-wellington"
  },
  {
    "city": "wellington",
    "slug": "chic-esthetique-wellington"
  },
  {
    "city": "wellington",
    "slug": "derma-designers-wellington"
  },
  {
    "city": "wellington",
    "slug": "laser-hair-removal"
  },
  {
    "city": "wellington",
    "slug": "luxe-aesthetics-lounge-wellington"
  },
  {
    "city": "wellington",
    "slug": "new-image-body-and-face-contouring-wellington"
  },
  {
    "city": "wellington",
    "slug": "palm-beach-anti-aging-and-regenerative-medicine-llc-wellington"
  },
  {
    "city": "wellington",
    "slug": "refresh-aesthetics-wellness-wellington-fl"
  },
  {
    "city": "wellington",
    "slug": "sassy-lashess-beauty-wellington"
  },
  {
    "city": "wellington",
    "slug": "sp-aesthetics-wellington-fl"
  },
  {
    "city": "wellington",
    "slug": "wycliffe-dental-center-wellington"
  },
  {
    "city": "west-hollywood",
    "slug": "botox-fillers"
  },
  {
    "city": "west-lake-hills",
    "slug": "austin-luxury-medspa-west-lake-hills-texas"
  },
  {
    "city": "west-linn",
    "slug": "access-total-body-med-spa-weight-loss-center-west-linn-oregon"
  },
  {
    "city": "west-palm-beach",
    "slug": "laser-hair-removal"
  },
  {
    "city": "west-palm-beach",
    "slug": "the-fountain-mri-full-body-scan-west-palm-beach-west-palm-beach-fl"
  },
  {
    "city": "weston",
    "slug": "skin-laser-the-moran-medical-corp-weston-fl"
  },
  {
    "city": "westwood",
    "slug": "skin-defyne-medspa-westwood-massachusetts"
  },
  {
    "city": "white-plains",
    "slug": "elite-beauty-medical-spa-white-plains"
  },
  {
    "city": "wilmington",
    "slug": "cosmetic-laser-solutions-medspa-ma-ri-wilmington-massachusetts"
  },
  {
    "city": "winter-park",
    "slug": "180-medspa-winter-park-fl"
  },
  {
    "city": "winter-park",
    "slug": "aesthetic-lane-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "allure-lounge-wellness-bar-winter-park-fl"
  },
  {
    "city": "winter-park",
    "slug": "bodenvy-coolsculpting-weight-loss-hormone-therapy-orlando-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "chemical-peels"
  },
  {
    "city": "winter-park",
    "slug": "coolsculpting"
  },
  {
    "city": "winter-park",
    "slug": "cosmetic-skin-laser-center-winter-park-fl"
  },
  {
    "city": "winter-park",
    "slug": "dr-phillips-aesthetics-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "drip-vibe-wellness-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "emerald-medical-center-and-spa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "euro-day-spa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "formah-body-sculpting-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "hydrafacial"
  },
  {
    "city": "winter-park",
    "slug": "iv-therapy"
  },
  {
    "city": "winter-park",
    "slug": "js-healthcare-med-spa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "look-lab-med-spa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "orlando-florida-plastic-surgery-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "peptide-therapy"
  },
  {
    "city": "winter-park",
    "slug": "polished-beauty-medspa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "restore-hyper-wellness-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "serotonin-centers-med-spa-winter-park-winter-park-fl"
  },
  {
    "city": "winter-park",
    "slug": "skinceuticals-skinlab-winter-park-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "the-wellspa-by-iv-wellness-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "vitalounge-winter-park-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "windermere-medical-spa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "winter-park-chiropractic-acupuncture-center-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "winter-park-laser-anti-aging-center-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "winter-park-medspa-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "winter-park-regenerative-medicine-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "winter-park-skin-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "wymore-laser-anti-aging-medicine-in-winter-park-fl-winter-park"
  },
  {
    "city": "winter-park",
    "slug": "wymore-laser-anti-aging-medicine-in-winter-park-fl-winter-park-fl"
  },
  {
    "city": "zephyrhills",
    "slug": "florida-face-and-body-zephyrhills"
  },
  {
    "city": "zephyrhills",
    "slug": "florida-face-and-body-zephyrhills-fl"
  },
  {
    "city": "zephyrhills",
    "slug": "mandala-massage-zephyrhills"
  },
  {
    "city": "zephyrhills",
    "slug": "quench-hydration-wellness-zephyrhills"
  }
]

/** Top city pages to pre-render at build time */
export const TOP_CITY_PARAMS: CityParam[] = [
  {
    "city": "winter-park"
  },
  {
    "city": "dallas"
  },
  {
    "city": "san-antonio"
  },
  {
    "city": "charlotte"
  },
  {
    "city": "naples"
  },
  {
    "city": "deerfield-beach"
  },
  {
    "city": "houston"
  },
  {
    "city": "miami-beach"
  },
  {
    "city": "atlanta"
  },
  {
    "city": "nashville"
  },
  {
    "city": "jupiter"
  },
  {
    "city": "denver"
  },
  {
    "city": "the-villages"
  },
  {
    "city": "st-petersburg"
  },
  {
    "city": "chicago"
  },
  {
    "city": "austin"
  },
  {
    "city": "tampa"
  },
  {
    "city": "pinecrest"
  },
  {
    "city": "minneapolis"
  },
  {
    "city": "miami-lakes"
  },
  {
    "city": "arlington"
  },
  {
    "city": "san-diego"
  },
  {
    "city": "new-york"
  },
  {
    "city": "hallandale-beach"
  },
  {
    "city": "tempe"
  },
  {
    "city": "north-miami"
  },
  {
    "city": "scottsdale"
  },
  {
    "city": "miami"
  },
  {
    "city": "lake-worth"
  },
  {
    "city": "long-island-city"
  },
  {
    "city": "fort-pierce"
  },
  {
    "city": "wellington"
  },
  {
    "city": "bal-harbour"
  },
  {
    "city": "las-vegas"
  },
  {
    "city": "pompano-beach"
  },
  {
    "city": "philadelphia"
  },
  {
    "city": "san-francisco"
  },
  {
    "city": "north-miami-beach"
  },
  {
    "city": "phoenix"
  },
  {
    "city": "lakeland"
  }
]
